#!/usr/bin/env bash
set -euo pipefail

echo "=============================================="
echo " CENTRO DE OPERACIONES NOVA"
echo "=============================================="
echo ""
echo "Estado operativo de Hocker ONE:"
echo ""
echo "  1. Pulso de Produccion"
echo "     Revisa que Hocker ONE responda correctamente."
echo ""
echo "  2. Blindaje del Sistema"
echo "     Confirma rutas protegidas, accesos y readiness."
echo ""
echo "  3. Candado de Base de Datos"
echo "     Evita acciones peligrosas sobre Supabase."
echo ""
echo "  4. Validacion Total HOCKER"
echo "     Ejecuta revision completa antes de cerrar un sprint."
echo ""
echo "Regla principal:"
echo "  Hocker ONE debe operar con lenguaje ejecutivo, limpio y no tecnico en la capa visual."
echo ""
echo "Regla de seguridad:"
echo "  NOVA puede vigilar, diagnosticar y reportar; cambios criticos requieren aprobacion."
echo "=============================================="
