-- HOCKER migration provenance placeholder.
-- Production ledger version: 20260830153247
-- Name: revoke_dead_public_agi_catalog_view_grants
-- Historical SQL source was externally applied and is unavailable in accessible Git history.
-- DO NOT reconstruct or infer the original DDL here.
-- This file is intentionally comment-only so the repository tracks the applied version
-- without claiming that the historical SQL has been recovered.
