-- Structural validation for the 16-AGI canon.
create or replace view public.v_agi_canon_completeness as select '12.6C.1B'::text canon_version,(select count(*) from public.agis where id in ('nova','syntia','vertx','jurix','curvewind','numia','nova_ads','candy','pro_ia','hostia','trackhok','nexpa','chido_wins','chido_gerente','shadows','revia'))::integer registry_profiles,(select count(*) from public.agi_agents where project_id='hocker-one' and agi_id in ('nova','syntia','vertx','jurix','curvewind','numia','nova_ads','candy','pro_ia','hostia','trackhok','nexpa','chido_wins','chido_gerente','shadows','revia'))::integer runtime_agents,(select count(*) from public.agi_agents where project_id='hocker-one' and agi_id not in ('nova','syntia','vertx','jurix','curvewind','numia','nova_ads','candy','pro_ia','hostia','trackhok','nexpa','chido_wins','chido_gerente','shadows','revia'))::integer alias_agents,(select count(*) from public.agi_agent_tools where project_id='hocker-one' and agi_id not in ('nova','syntia','vertx','jurix','curvewind','numia','nova_ads','candy','pro_ia','hostia','trackhok','nexpa','chido_wins','chido_gerente','shadows','revia'))::integer alias_tool_assignments,(select count(*) from public.agi_memory_mirror where project_id='hocker-one' and canonical_memory_key like 'canon.profile.%.12_6c_1b' and active)::integer canonical_memories,(select count(*) from public.agi_update_feed where project_id='hocker-one' and canonical_memory_key like 'canon.profile.%.12_6c_1b' and status='active')::integer specialized_feeds,(select count(*) from public.agi_agent_tools where project_id='hocker-one' and enabled)::integer enabled_tool_assignments,(select count(*) from public.agi_agent_tools where project_id='hocker-one' and agi_id='shadows' and enabled)::integer shadows_enabled_tools;
create or replace function public.validate_hocker_agi_canon()
returns table(check_name text,ok boolean,actual integer,expected integer,detail text)
language sql stable security definer set search_path=public as $$
 select 'registry_profiles',registry_profiles=16,registry_profiles,16,'Exactly 16 canonical rows.' from public.v_agi_canon_completeness union all
 select 'runtime_agents',runtime_agents=16,runtime_agents,16,'Exactly 16 runtime agents.' from public.v_agi_canon_completeness union all
 select 'alias_agents',alias_agents=0,alias_agents,0,'No alias identities.' from public.v_agi_canon_completeness union all
 select 'alias_tool_assignments',alias_tool_assignments=0,alias_tool_assignments,0,'Tools use canonical IDs.' from public.v_agi_canon_completeness union all
 select 'canonical_memories',canonical_memories=16,canonical_memories,16,'One canonical memory per AGI.' from public.v_agi_canon_completeness union all
 select 'specialized_feeds',specialized_feeds=16,specialized_feeds,16,'One specialized feed per AGI.' from public.v_agi_canon_completeness union all
 select 'shadows_fail_closed',shadows_enabled_tools=0,shadows_enabled_tools,0,'Shadows has no enabled executor.' from public.v_agi_canon_completeness;
$$;
revoke all on function public.validate_hocker_agi_canon() from public,anon;
grant execute on function public.validate_hocker_agi_canon() to authenticated,service_role;
grant select on public.v_agi_canon_completeness to authenticated,service_role;
insert into public.agi_integration_checks(project_id,tool_key,status,configured,last_checked_at,message,meta) values('hocker-one','ai_gateway','auth_failed',true,now(),'Last real production attempt rejected available Vercel credentials. Awaiting verified completion.',jsonb_build_object('provider','vercel-ai-gateway','canon_version','12.6C.1B','secret_material_logged',false));
comment on view public.v_agi_canon_completeness is 'Structural audit for the HOCKER 16-AGI canon. Model verification is separate.';
